import test from 'node:test';import assert from 'node:assert/strict';
import {buildPlan} from '../scripts/beta-cutover-package.mjs';
import {audit} from '../scripts/audit-beta-preparation.mjs';
import {target,probeTarget} from '../scripts/beta-cutover-preflight.mjs';
const inventory=audit(),revision='a'.repeat(40);
test('fresh-project package includes whole baseline, incremental plan includes all reviewed successors',()=>{const fresh=buildPlan(probeTarget.projectRef,inventory,revision),old=buildPlan(target.projectRef,inventory,revision);assert.equal(fresh.migrations.length,33);assert.equal(old.migrations.length,17);assert.equal(fresh.migrations[0].version,'20260827010000');assert.equal(fresh.migrations.at(-1).version,'20260920221005');assert.ok(fresh.migrations.every(m=>m.rehearsal==='NOT_ATTESTED'));});
test('unknown/prod target or migration drift cannot generate a deployment plan',()=>{assert.throws(()=>buildPlan(target.productionRef,inventory,revision));assert.throws(()=>buildPlan('x'.repeat(20),inventory,revision));assert.throws(()=>buildPlan(probeTarget.projectRef,{...inventory,all_migrations:inventory.all_migrations.slice(1)},revision));});
test('new-project rollback cannot accidentally redeploy old project configuration',()=>{const p=buildPlan(probeTarget.projectRef,inventory,revision);assert.equal(p.commands.edge_rollback,null);assert.ok(p.commands.edge_deploy.includes(probeTarget.projectRef));assert.ok(!p.commands.edge_deploy.includes(target.projectRef));assert.equal(p.remote_mutations,0);assert.equal(p.remote_e2e.status,'PREPARED_NOT_EXECUTED');assert.equal(p.rollback.data_policy,'CODE_CONFIG_ONLY_NO_SQL_REWIND_OR_ROW_DELETE');assert.ok(!JSON.stringify(p.commands).includes('--prune'));});
test('prototype keys are never authorized targets',()=>{for(const ref of ['toString','__proto__','constructor'])assert.throws(()=>buildPlan(ref,inventory,revision),/UNAPPROVED_BETA_TARGET/);});
