import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
const read=p=>fs.readFileSync(p,'utf8');
test('browser wait follows existing 30s transport contract and preserves intentional A/B contexts',()=>{
 const runner=read('scripts/test-manual-sql-e2e.mjs');assert.match(runner,/p.setDefaultTimeout\(32000\)/);assert.match(runner,/preservePrevious=false/);assert.match(runner,/for\(const entry of contexts\)await retainContext\(entry\)/);
 assert.match(read('scripts/local-engine-web.js'),/AbortSignal.timeout\(30000\)/);
 assert.match(read('scripts/manual-observation-browser-gates.mjs'),/preservePrevious:true/);
});
test('hosted runtime never switches role, grants privileges, or falls back to privileged SQL',()=>{const s=read('supabase/functions/mobile-health-beta/hosted-manual-bootstrap.ts')+read('supabase/functions/mobile-health-beta/manual-sql-context.ts');assert.doesNotMatch(s,/set local role|grant service_role|bypassrls\s*[:=]\s*true/i);assert.match(s,/has_membership/);assert.match(s,/role.effective!==expectedLogin/);assert.match(s,/rejectUnauthorized:true,ca:HOSTED_DATABASE_CA/);});
test('context binds two verified hashes transaction locally, never canonical body user_id',()=>{const s=read('supabase/functions/mobile-health-beta/manual-sql-context.ts');assert.match(s,/AsyncLocalStorage/);assert.match(s,/contexts.run\(Object.freeze/);assert.match(s,/set_config\('health.manual.subject',[\s\S]*?,true\)/);assert.doesNotMatch(s,/payload|request\.json|set_config\('.*user_id/);assert.match(read('supabase/functions/mobile-health-beta/local-engine-runtime.ts'),/this.sql.withWeb\(identity,dispatch\)/);});
test('successor has no elevated role membership, no new definer, and no destructive data operation',()=>{const s=read('supabase/migrations/20260916144345_manual_runtime_least_privilege.sql');assert.doesNotMatch(s,/security definer|grant service_role|\btruncate\b|\bdrop\b|delete from/i);assert.match(s,/security invoker/g);assert.match(s,/grant select,insert on public.engine_output_history/);assert.match(s,/manual_catalog_delete/);assert.match(s,/u.status='ACTIVE'/);});
test('bundled public CA is a valid CA with OpenSSL-verified DER fingerprint and not a private key',()=>{const s=read('supabase/functions/mobile-health-beta/hosted-database-ca.ts'),pem=s.match(/-----BEGIN CERTIFICATE-----[\s\S]*?-----END CERTIFICATE-----/)[0];const cert=new crypto.X509Certificate(pem);assert.equal(cert.ca,true);assert.match(cert.subject,/Supabase/);assert.ok(Date.parse(cert.validTo)>Date.now());assert.doesNotMatch(s,/PRIVATE KEY/);assert.equal(cert.fingerprint256,'80:70:25:AD:50:D4:ED:21:9D:2C:9C:7D:29:9C:00:4F:82:4E:B0:0C:F7:F6:5A:FE:F6:07:D0:7B:72:E6:CA:FA');});
